// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0VN2W-wY4m52bOR-lHcXq89uzcqrEKJk',
    appId: '1:267618780016:web:a64e1f49193d552a5545b5',
    messagingSenderId: '267618780016',
    projectId: 'cmsc23-todo-app-hannahunite',
    authDomain: 'cmsc23-todo-app-hannahunite.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-hannahunite.appspot.com',
    measurementId: 'G-S0YF9E34BR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZTEuPSW7REO-tIQiVArZyw1q3aNCvfx4',
    appId: '1:267618780016:android:ae527e40f6e90d8f5545b5',
    messagingSenderId: '267618780016',
    projectId: 'cmsc23-todo-app-hannahunite',
    storageBucket: 'cmsc23-todo-app-hannahunite.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNPxLwXeSupxVHv2Ut_LrX3PnrVMZNn0I',
    appId: '1:267618780016:ios:7cc0d707ea50011c5545b5',
    messagingSenderId: '267618780016',
    projectId: 'cmsc23-todo-app-hannahunite',
    storageBucket: 'cmsc23-todo-app-hannahunite.appspot.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNPxLwXeSupxVHv2Ut_LrX3PnrVMZNn0I',
    appId: '1:267618780016:ios:7cc0d707ea50011c5545b5',
    messagingSenderId: '267618780016',
    projectId: 'cmsc23-todo-app-hannahunite',
    storageBucket: 'cmsc23-todo-app-hannahunite.appspot.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0VN2W-wY4m52bOR-lHcXq89uzcqrEKJk',
    appId: '1:267618780016:web:976e11cc9b7e4e535545b5',
    messagingSenderId: '267618780016',
    projectId: 'cmsc23-todo-app-hannahunite',
    authDomain: 'cmsc23-todo-app-hannahunite.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-hannahunite.appspot.com',
    measurementId: 'G-KTKVK9QZ5F',
  );
}
